ERROR 2025-08-08 10:23:12 view_Nfactor form_valid FATAL: Exception during atomic transaction: (1364, "Field 'status' doesn't have a default value")
Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\connections.py", line 280, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
MySQLdb.IntegrityError: (1364, "Field 'status' doesn't have a default value")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\tankhah\Factor\NF\view_Nfactor.py", line 358, in form_valid
    self.object.save()
    ~~~~~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\tankhah\models.py", line 1026, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\base.py", line 892, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\base.py", line 998, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\base.py", line 1161, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\base.py", line 1202, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\connections.py", line 280, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.IntegrityError: (1364, "Field 'status' doesn't have a default value")
ERROR 2025-08-08 10:29:32 view_Nfactor form_valid FATAL: Exception during atomic transaction: (1364, "Field 'status' doesn't have a default value")
Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\connections.py", line 280, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
MySQLdb.IntegrityError: (1364, "Field 'status' doesn't have a default value")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\tankhah\Factor\NF\view_Nfactor.py", line 358, in form_valid
    self.object.save()
    ~~~~~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\tankhah\models.py", line 1027, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\base.py", line 892, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\base.py", line 998, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\base.py", line 1161, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\base.py", line 1202, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\connections.py", line 280, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.IntegrityError: (1364, "Field 'status' doesn't have a default value")
ERROR 2025-08-08 10:32:24 view_Nfactor form_valid FATAL: Exception during atomic transaction: (1364, "Field 'status' doesn't have a default value")
Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\connections.py", line 280, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
MySQLdb.IntegrityError: (1364, "Field 'status' doesn't have a default value")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\tankhah\Factor\NF\view_Nfactor.py", line 359, in form_valid
    self.object.save()
    ~~~~~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\tankhah\models.py", line 1027, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\base.py", line 892, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\base.py", line 998, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\base.py", line 1161, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\base.py", line 1202, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\connections.py", line 280, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.IntegrityError: (1364, "Field 'status' doesn't have a default value")
ERROR 2025-08-08 10:33:24 view_Nfactor form_valid FATAL: Exception during atomic transaction: Cannot assign "'DRAFT'": "Factor.status" must be a "Status" instance.
Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\tankhah\Factor\NF\view_Nfactor.py", line 356, in form_valid
    self.object.status = initial_factor_status   # <-- **اصلاح کلیدی**
    ^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 287, in __set__
    raise ValueError(
    ...<7 lines>...
    )
ValueError: Cannot assign "'DRAFT'": "Factor.status" must be a "Status" instance.
ERROR 2025-08-08 10:34:12 view_Nfactor form_valid FATAL: Exception during atomic transaction: Cannot assign "1": "Factor.status" must be a "Status" instance.
Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\tankhah\Factor\NF\view_Nfactor.py", line 356, in form_valid
    self.object.status = initial_factor_status   # <-- **اصلاح کلیدی**
    ^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\fields\related_descriptors.py", line 287, in __set__
    raise ValueError(
    ...<7 lines>...
    )
ValueError: Cannot assign "1": "Factor.status" must be a "Status" instance.
ERROR 2025-08-08 10:37:03 view_Nfactor form_valid FATAL: Exception during atomic transaction: (1364, "Field 'status' doesn't have a default value")
Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\connections.py", line 280, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
MySQLdb.IntegrityError: (1364, "Field 'status' doesn't have a default value")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\tankhah\Factor\NF\view_Nfactor.py", line 360, in form_valid
    self.object.save()
    ~~~~~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\tankhah\models.py", line 1027, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\base.py", line 892, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\base.py", line 998, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\base.py", line 1161, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\base.py", line 1202, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\connections.py", line 280, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.IntegrityError: (1364, "Field 'status' doesn't have a default value")
ERROR 2025-08-08 10:48:01 view_Nfactor form_valid FATAL: Exception during atomic transaction: (1364, "Field 'status' doesn't have a default value")
Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\connections.py", line 280, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
MySQLdb.IntegrityError: (1364, "Field 'status' doesn't have a default value")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\tankhah\Factor\NF\view_Nfactor.py", line 361, in form_valid
    self.object.save()
    ~~~~~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\tankhah\models.py", line 1028, in save
    super().save(*args, **kwargs)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\base.py", line 892, in save
    self.save_base(
    ~~~~~~~~~~~~~~^
        using=using,
        ^^^^^^^^^^^^
    ...<2 lines>...
        update_fields=update_fields,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\base.py", line 998, in save_base
    updated = self._save_table(
        raw,
    ...<4 lines>...
        update_fields,
    )
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\base.py", line 1161, in _save_table
    results = self._do_insert(
        cls._base_manager, using, fields, returning_fields, raw
    )
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\base.py", line 1202, in _do_insert
    return manager._insert(
           ~~~~~~~~~~~~~~~^
        [self],
        ^^^^^^^
    ...<3 lines>...
        raw=raw,
        ^^^^^^^^
    )
    ^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\query.py", line 1847, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1836, in execute_sql
    cursor.execute(sql, params)
    ~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 122, in execute
    return super().execute(sql, params)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 79, in execute
    return self._execute_with_wrappers(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        sql, params, many=False, executor=self._execute
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 92, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 100, in _execute
    with self.db.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\utils.py", line 105, in _execute
    return self.cursor.execute(sql, params)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 76, in execute
    return self.cursor.execute(query, args)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\cursors.py", line 330, in _query
    db.query(q)
    ~~~~~~~~^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\connections.py", line 280, in query
    _mysql.connection.query(self, query)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
django.db.utils.IntegrityError: (1364, "Field 'status' doesn't have a default value")
