ERROR 2025-06-27 17:51:16 rcms_custom_filters format_negative Error formatting number -: could not convert string to float: '-'
ERROR 2025-06-27 17:51:16 rcms_custom_filters format_negative Error formatting number تست ردیف: could not convert string to float: 'تست ردیف'
ERROR 2025-06-27 18:42:25 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:42:25 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:42:25 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:42:25 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:42:25 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:42:25 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:42:26 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:42:26 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:42:26 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:42:26 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:42:26 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:42:26 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:02 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:02 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:02 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:02 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:02 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:02 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:02 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:02 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:02 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:03 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:03 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:03 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:03 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:03 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:03 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:03 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:03 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:03 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:53 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:53 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:53 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:53 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:53 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:53 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:53 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:53 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:43:53 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:15 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:15 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:15 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:15 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:15 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:15 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:15 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:15 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:15 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:15 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:15 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:15 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:15 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:15 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:15 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:15 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:15 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:15 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:18 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:18 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:18 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:18 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:18 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:18 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:36 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:36 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:36 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:36 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:36 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:36 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:36 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:36 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:36 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:36 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:36 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:36 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:52 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:52 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:52 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:52 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:52 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:44:52 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:45:01 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:45:01 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:45:01 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:45:01 rcms_custom_filters format_negative Error formatting number بازگشت مبلغ ۵۷۰,۰۰۰,۰۰۰ (پانصد و هفتاد میلیون) ریال از بودجه تخصیص یافته به سازمان «هتل لاله سرعین» برای پروژه «بازسازی هتل - طبقه سوم لاله سرعین» به دلیل «اتمام پروژه و وجود مانده».: could not convert string to float: 'بازگشت مبلغ ۵۷۰,۰۰۰,۰۰۰ (پانصد و هفتاد میلیون) ریال از بودجه تخصیص یافته به سازمان «هتل لاله سرعین» برای پروژه «بازسازی هتل - طبقه سوم لاله سرعین» به دلیل «اتمام پروژه و وجود مانده».'
ERROR 2025-06-27 18:45:01 rcms_custom_filters format_negative Error formatting number بازگشت مبلغ ۲۴,۰۰۰,۰۰۰ (بیست میلیون) ریال از بودجه تخصیص یافته به سازمان «هتل لاله سرعین» برای پروژه «بازسازی هتل - طبقه سوم لاله سرعین» به دلیل «اتمام پروژه و وجود مانده».: could not convert string to float: 'بازگشت مبلغ ۲۴,۰۰۰,۰۰۰ (بیست میلیون) ریال از بودجه تخصیص یافته به سازمان «هتل لاله سرعین» برای پروژه «بازسازی هتل - طبقه سوم لاله سرعین» به دلیل «اتمام پروژه و وجود مانده».'
ERROR 2025-06-27 18:45:01 rcms_custom_filters format_negative Error formatting number ۷۶,۰۰۰,۰۰۰: could not convert string to float: '۷۶,۰۰۰,۰۰۰'
ERROR 2025-06-27 18:45:01 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:45:01 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:45:01 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:45:01 rcms_custom_filters format_negative Error formatting number ایجاد فاکتور به شماره FAC-TNKH-14040318-HSarein-E-IT-001-14040404-HSarein-0001: could not convert string to float: 'ایجاد فاکتور به شماره FAC-TNKH-14040318-HSarein-E-IT-001-14040404-HSarein-0001'
ERROR 2025-06-27 18:45:01 rcms_custom_filters format_negative Error formatting number ایجاد فاکتور FAC-TNKH-14040318-HSarein-E-IT-001-14040318-HSarein-0001: could not convert string to float: 'ایجاد فاکتور FAC-TNKH-14040318-HSarein-E-IT-001-14040318-HSarein-0001'
ERROR 2025-06-27 18:45:01 rcms_custom_filters format_negative Error formatting number ایجاد فاکتور FAC-TNKH-14040315-HSarein-E-IT-001-14040315-HSarein-0002: could not convert string to float: 'ایجاد فاکتور FAC-TNKH-14040315-HSarein-E-IT-001-14040315-HSarein-0002'
ERROR 2025-06-27 18:45:01 rcms_custom_filters format_negative Error formatting number ایجاد فاکتور FAC-TNKH-14040315-HSarein-E-IT-001-14040315-HSarein-0001: could not convert string to float: 'ایجاد فاکتور FAC-TNKH-14040315-HSarein-E-IT-001-14040315-HSarein-0001'
ERROR 2025-06-27 18:45:02 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:45:02 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:45:02 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:45:02 rcms_custom_filters format_negative Error formatting number بازگشت مبلغ ۵۷۰,۰۰۰,۰۰۰ (پانصد و هفتاد میلیون) ریال از بودجه تخصیص یافته به سازمان «هتل لاله سرعین» برای پروژه «بازسازی هتل - طبقه سوم لاله سرعین» به دلیل «اتمام پروژه و وجود مانده».: could not convert string to float: 'بازگشت مبلغ ۵۷۰,۰۰۰,۰۰۰ (پانصد و هفتاد میلیون) ریال از بودجه تخصیص یافته به سازمان «هتل لاله سرعین» برای پروژه «بازسازی هتل - طبقه سوم لاله سرعین» به دلیل «اتمام پروژه و وجود مانده».'
ERROR 2025-06-27 18:45:02 rcms_custom_filters format_negative Error formatting number بازگشت مبلغ ۲۴,۰۰۰,۰۰۰ (بیست میلیون) ریال از بودجه تخصیص یافته به سازمان «هتل لاله سرعین» برای پروژه «بازسازی هتل - طبقه سوم لاله سرعین» به دلیل «اتمام پروژه و وجود مانده».: could not convert string to float: 'بازگشت مبلغ ۲۴,۰۰۰,۰۰۰ (بیست میلیون) ریال از بودجه تخصیص یافته به سازمان «هتل لاله سرعین» برای پروژه «بازسازی هتل - طبقه سوم لاله سرعین» به دلیل «اتمام پروژه و وجود مانده».'
ERROR 2025-06-27 18:45:02 rcms_custom_filters format_negative Error formatting number ۷۶,۰۰۰,۰۰۰: could not convert string to float: '۷۶,۰۰۰,۰۰۰'
ERROR 2025-06-27 18:45:02 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:45:02 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:45:02 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:45:02 rcms_custom_filters format_negative Error formatting number ایجاد فاکتور به شماره FAC-TNKH-14040318-HSarein-E-IT-001-14040404-HSarein-0001: could not convert string to float: 'ایجاد فاکتور به شماره FAC-TNKH-14040318-HSarein-E-IT-001-14040404-HSarein-0001'
ERROR 2025-06-27 18:45:02 rcms_custom_filters format_negative Error formatting number ایجاد فاکتور FAC-TNKH-14040318-HSarein-E-IT-001-14040318-HSarein-0001: could not convert string to float: 'ایجاد فاکتور FAC-TNKH-14040318-HSarein-E-IT-001-14040318-HSarein-0001'
ERROR 2025-06-27 18:45:02 rcms_custom_filters format_negative Error formatting number ایجاد فاکتور FAC-TNKH-14040315-HSarein-E-IT-001-14040315-HSarein-0002: could not convert string to float: 'ایجاد فاکتور FAC-TNKH-14040315-HSarein-E-IT-001-14040315-HSarein-0002'
ERROR 2025-06-27 18:45:02 rcms_custom_filters format_negative Error formatting number ایجاد فاکتور FAC-TNKH-14040315-HSarein-E-IT-001-14040315-HSarein-0001: could not convert string to float: 'ایجاد فاکتور FAC-TNKH-14040315-HSarein-E-IT-001-14040315-HSarein-0001'
ERROR 2025-06-27 18:45:08 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:45:08 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:45:08 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:45:08 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:45:08 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:45:08 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:45:09 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:45:09 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:45:09 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:45:09 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:45:09 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 18:45:09 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 19:02:21 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 19:02:21 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 19:02:21 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 19:02:21 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 19:02:21 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-27 19:02:21 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-06-30 15:08:58 models calculate_final_version خطا در محاسبه نسخه نهایی: (2002, "Can't connect to server on '127.0.0.1' (10061)")
Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
MySQLdb.OperationalError: (2002, "Can't connect to server on '127.0.0.1' (10061)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\version_tracker\models.py", line 445, in calculate_final_version
    max_major = AppVersion.objects.aggregate(max_major=Max('major'))['max_major']
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\query.py", line 604, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\sql\query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1572, in execute_sql
    cursor = self.connection.cursor()
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 320, in cursor
    return self._cursor()
           ~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 296, in _cursor
    self.ensure_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: (2002, "Can't connect to server on '127.0.0.1' (10061)")
ERROR 2025-06-30 15:09:00 models calculate_final_version خطا در محاسبه نسخه نهایی: (2002, "Can't connect to server on '127.0.0.1' (10061)")
Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
MySQLdb.OperationalError: (2002, "Can't connect to server on '127.0.0.1' (10061)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\version_tracker\models.py", line 445, in calculate_final_version
    max_major = AppVersion.objects.aggregate(max_major=Max('major'))['max_major']
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\query.py", line 604, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\sql\query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1572, in execute_sql
    cursor = self.connection.cursor()
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 320, in cursor
    return self._cursor()
           ~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 296, in _cursor
    self.ensure_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: (2002, "Can't connect to server on '127.0.0.1' (10061)")
ERROR 2025-06-30 15:46:19 models calculate_final_version خطا در محاسبه نسخه نهایی: (1049, "Unknown database 'tankhasystem'")
Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
MySQLdb.OperationalError: (1049, "Unknown database 'tankhasystem'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\version_tracker\models.py", line 445, in calculate_final_version
    max_major = AppVersion.objects.aggregate(max_major=Max('major'))['max_major']
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\query.py", line 604, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\sql\query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1572, in execute_sql
    cursor = self.connection.cursor()
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 320, in cursor
    return self._cursor()
           ~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 296, in _cursor
    self.ensure_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: (1049, "Unknown database 'tankhasystem'")
ERROR 2025-06-30 15:46:20 models calculate_final_version خطا در محاسبه نسخه نهایی: (1049, "Unknown database 'tankhasystem'")
Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
MySQLdb.OperationalError: (1049, "Unknown database 'tankhasystem'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\version_tracker\models.py", line 445, in calculate_final_version
    max_major = AppVersion.objects.aggregate(max_major=Max('major'))['max_major']
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\query.py", line 604, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\sql\query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1572, in execute_sql
    cursor = self.connection.cursor()
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 320, in cursor
    return self._cursor()
           ~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 296, in _cursor
    self.ensure_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: (1049, "Unknown database 'tankhasystem'")
ERROR 2025-06-30 15:52:15 models calculate_final_version خطا در محاسبه نسخه نهایی: (1049, "Unknown database 'tankhasystem'")
Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
MySQLdb.OperationalError: (1049, "Unknown database 'tankhasystem'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\version_tracker\models.py", line 445, in calculate_final_version
    max_major = AppVersion.objects.aggregate(max_major=Max('major'))['max_major']
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\query.py", line 604, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\sql\query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1572, in execute_sql
    cursor = self.connection.cursor()
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 320, in cursor
    return self._cursor()
           ~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 296, in _cursor
    self.ensure_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: (1049, "Unknown database 'tankhasystem'")
ERROR 2025-06-30 15:52:15 models calculate_final_version خطا در محاسبه نسخه نهایی: (1049, "Unknown database 'tankhasystem'")
Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
MySQLdb.OperationalError: (1049, "Unknown database 'tankhasystem'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\version_tracker\models.py", line 445, in calculate_final_version
    max_major = AppVersion.objects.aggregate(max_major=Max('major'))['max_major']
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\query.py", line 604, in aggregate
    return self.query.chain().get_aggregation(self.db, kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\sql\query.py", line 616, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\models\sql\compiler.py", line 1572, in execute_sql
    cursor = self.connection.cursor()
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 320, in cursor
    return self._cursor()
           ~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 296, in _cursor
    self.ensure_connection()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 278, in ensure_connection
    with self.wrap_database_errors:
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 279, in ensure_connection
    self.connect()
    ~~~~~~~~~~~~^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\base\base.py", line 256, in connect
    self.connection = self.get_new_connection(conn_params)
                      ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\utils\asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\db\backends\mysql\base.py", line 256, in get_new_connection
    connection = Database.connect(**conn_params)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\MySQLdb\connections.py", line 200, in __init__
    super().__init__(*args, **kwargs2)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: (1049, "Unknown database 'tankhasystem'")
ERROR 2025-07-01 08:28:21 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-07-01 08:28:21 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-07-01 08:28:21 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-07-01 08:28:21 rcms_custom_filters format_negative Error formatting number : could not convert string to float: ''
ERROR 2025-07-01 08:28:21 ComprehensiveBudgetReportView get خطای بحرانی در APIOrganizationsForPeriodView برای period_pk=19: Reverse for 'api_budget_items_for_org_period' not found. 'api_budget_items_for_org_period' is not a valid view function or pattern name.
Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\reports\ComprehensiveBudgetReportView.py", line 196, in get
    'budget_items_ajax_url': reverse('api_budget_items_for_org_period',
                             ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                     kwargs={'period_pk': period.pk,
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                             'org_pk': org_sum['organization__id']})
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'api_budget_items_for_org_period' not found. 'api_budget_items_for_org_period' is not a valid view function or pattern name.
ERROR 2025-07-01 08:28:24 ComprehensiveBudgetReportView get خطای بحرانی در APIOrganizationsForPeriodView برای period_pk=15: Reverse for 'api_budget_items_for_org_period' not found. 'api_budget_items_for_org_period' is not a valid view function or pattern name.
Traceback (most recent call last):
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\reports\ComprehensiveBudgetReportView.py", line 196, in get
    'budget_items_ajax_url': reverse('api_budget_items_for_org_period',
                             ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                     kwargs={'period_pk': period.pk,
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                             'org_pk': org_sum['organization__id']})
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Design & Source Code\Source Coding\Tanbakhsystem\venv\Lib\site-packages\django\urls\resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'api_budget_items_for_org_period' not found. 'api_budget_items_for_org_period' is not a valid view function or pattern name.
